### ISSUE TITLE
Histogram for AOC

### ISSUE THREAD

**Issue by vcellmike** [MolClustPy/SpringSaLaD-Python-Viz#6]
Use time as an argument, and plot AOC histogram at a given time point. Plot header with the time and AOC value

See if  OVERALL should be used instead of MEAN to compute AOC, see the difference in outputs (it's likely not significant, but still needs to be investigated).

**Comment by Hlpred** [comment]
Setting the time_ms (milliseconds) variable in the histogram.ipynb file now selects the desired point in time for the histogram. The title is plotted with a modified version of the Molclustpy plotClusterDist function. ACO isn't in the title because it's right next to it in the legend. Lastly, it looks like the overall frequency finds the frequency of all the runs together whereas the average frequency averages the individual frequencies of each run. I left it as average for now because I don't see anything wrong with that way of calculating it.

![image](https://github.com/MolClustPy/SpringSaLaD-Python-Viz/assets/71465959/ec679fb6-d72f-4bf2-9013-f24fa423ed9b)
